### ISSUE TITLE
Error when importing component.

### ISSUE THREAD

**Issue by realav** [mikesmit/nextjs-blog-starter-mdx#1]
I am getting this error when importing the **Next Link component** into the .mdx file.
`import Link from "next/link";`

```
ReferenceError: require is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source

lib/mdxSerialization.js (12:9) @ async mdxToString

  10 |  */
  11 | export async function mdxToString(mdx) {
> 12 |   return await renderToString(mdx, {components})
     |         ^
  13 | }
  14 | 
  15 | /**
```

**Comment by mikesmit** [comment]
https://github.com/mikesmit/nextjs-blog-starter-mdx/tree/link-test works for me.

**Comment by realav** [comment]
Thank you. 
So you imported the Link module externally from **mdxSerialization.js**.
Is there any way to directly import modules in .mdx?

**Comment by mikesmit** [comment]
This is the way to do it if you want to support remote content. If you want to just use local content you use @next/mdx and write .mdx pages more or less the same way you write jsx pages.

**Comment by mikesmit** [comment]
Closing out since I haven't heard back
